/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include "stm32f407xx.h"
#include <string.h>

void delay()
{
	for (volatile int i = 0; i < 500000; i++);
}

//To Test SPI Send data code
	void SPI2_GPIO_Init(void)
	{
		GPIO_Handle_t SPI_Pins;
		SPI_Pins.pGPIOx = GPIOB;
		SPI_Pins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
		SPI_Pins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
		SPI_Pins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
		SPI_Pins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
		SPI_Pins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;

		//SCLK Pin
		SPI_Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
		GPIO_Init(&SPI_Pins);

		//MOSI
		SPI_Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
		GPIO_Init(&SPI_Pins);

		//NSS
		//SPI_Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
		//GPIO_Init(&SPI_Pins);
	}

	void SPI2_Init()
	{
		SPI_Handle_t SPI2Handle;
		SPI2Handle.pSPIx = SPI2;
		SPI2Handle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
		SPI2Handle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
		SPI2Handle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2; //Generates SCLK of 8Mhz
		SPI2Handle.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
		SPI2Handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
		SPI2Handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
		SPI2Handle.SPIConfig.SPI_SSM = SPI_SSM_EN; 	//Software slave management enabled for NSS pin
		SPI_Init(&SPI2Handle);
	}


int main(void)
{
	char data[] = "Hello world";
	//SPI_Send data
	SPI2_GPIO_Init();

	SPI2_Init();

	//This makes NSS internally high which avoids MODF(mode fault)
	SPI_SSIConfig(SPI2,ENABLE);

	//Enable the SPI peripheral
	SPI_PeripheralControl(SPI2,ENABLE);

	SPI_SendData(SPI2, (uint8_t*)data, strlen(data));

	SPI_PeripheralControl(SPI2,DISABLE);



	while(1);







	/*GPIO_Handle_t GpioLed,GpioBtn;

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_PeriClockControl(GPIOA, ENABLE);

	//Configure the button
	GpioBtn.pGPIOx = GPIOA;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
		GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
		GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
		GPIO_Init(&GpioBtn);



	// Configure PD13 (Orange LED)
	GpioLed.pGPIOx = GPIOD;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIO_Init(&GpioLed);

	// Configure PD14 (Red LED)
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	GPIO_Init(&GpioLed);

	// Configure PD12 (Green LED)
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIO_Init(&GpioLed);

	// Configure PD12 (Green LED)
		GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
		GPIO_Init(&GpioLed);

	while(1)
	{
		if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0) == SET)
		{
			delay();
		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, SET);
		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_13, SET);
		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_14, SET);
		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_15, SET);

		delay();
		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, RESET);
				GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_13, RESET);
				GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_14, RESET);
				GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_15, RESET);
				delay();
		}
		else
		{

			GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, RESET);
					GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_13, RESET);
					GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_14, RESET);
					GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_15, RESET);
		}


	}*/





	}


